Overwrite TerraScan output files (optional)
IGNF/coclico pull request #29
Opened 2023-09-29 09:51 UTC by leavauchier

[x] refactor jobs creation to be able to add preprocessing jobs for each classification
[] add preprocessing jobs

2023-10-06 10:07 UTC, gliegard requested changes

2023-10-06 10:07 UTC, gliegard commented on coclico/unlock.py
> +{pdaltools_image}:{pdaltools_version}
Je trouve ça dommage d'avoir une à gérer une autre image docker, seulement pour cette fonction d'unlock qui fait 3 lignes et n'a pas de dépendances.

Une alternative serait de mettre la lib `ign-pdal-tools` en dépendance de coclico dans le fichier `environment.yml`.
Ainsi, l'image Docker coclico porterait cette fonction d'unlock dans son environnement conda.

ça permettrait 
- d'utiliser la meme image docker pour les calculs faits par coclico
- d'éviter d'avoir une image de plus à gérer au niveau du déploiement sur les noeuds de calcul
- d'éviter de déployer une image docker de 600 Mo pour une petite fonction de 3 lignes.

2023-10-06 10:07 UTC, gliegard commented on coclico/main.py
> +        + "ATTENTION: Les fichiers d'entrée seront écrasés !",
```suggestion
        + "Attention: l'entête des fichiers d'entrée sera modifiée !",
```

2023-10-06 10:07 UTC, gliegard commented on README.md
> +                        ATTENTION: Les fichiers d'entrée seront écrasés !
```suggestion
                        Attention: l'entête des fichiers d'entrée sera modifiée !
```

2023-10-09 09:19 UTC, leavauchier commented on coclico/unlock.py
> +{pdaltools_image}:{pdaltools_version}
c'est modifié

2023-10-09 09:46 UTC, gliegard approved these changes

2023-10-09 09:48 UTC, merged