Refactoring: prepare malt0
IGNF/coclico pull request #41
Opened 2023-11-22 15:42 UTC by leavauchier

- Move consistency map out of mpla0 as it will be used in malt0
- add `is_ref` flag for intrinsic metric in order to behave differently when running on reference data

2023-11-22 18:14 UTC, gliegard requested changes

2023-11-22 18:14 UTC, gliegard commented on coclico/metrics/metric.py
> +        self, name: str, tile_names: List[str], input_path: Path, out_path: Path, is_ref: bool
Pourquoi ajouter ce paramètre ? Il n'est jamais utilsé.

2023-11-23 08:13 UTC, leavauchier commented on coclico/metrics/metric.py
> +        self, name: str, tile_names: List[str], input_path: Path, out_path: Path, is_ref: bool
parce que j'en ai besoin dans la prochaine métrique (en fait je ne savais pas si je devais le mettre là ou avec la PR suivante parce que ça impacte toutes les métriques).
En fait, dans la métrique suivante j'ai besoin de la carte d'occupation uniquement de la référence, et c'est le moyen que j'ai trouvé de différencier les 2 pour ne faire le calcul que quand ce paramètre est à `True`

2023-11-23 10:07 UTC, gliegard approved these changes

2023-11-23 10:51 UTC, merged